"""Data schemas and types for TaintBox."""

from __future__ import annotations

import time
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class TrustLevel(str, Enum):
    TRUSTED = "TRUSTED"        # Verified internal / trusted system prompts
    INTERNAL = "INTERNAL"      # Generated by sandbox during execution
    UNTRUSTED = "UNTRUSTED"    # Ingested from external sources (web, files)
    HOSTILE = "HOSTILE"        # Confirmed malicious / attack payload


class ProvenanceTag(str, Enum):
    SYSTEM = "SYSTEM"
    USER = "USER"
    UNTRUSTED_WEB = "UNTRUSTED_WEB"
    EXTERNAL_FILE = "EXTERNAL_FILE"
    DERIVED = "DERIVED"


class ProvenanceRecord(BaseModel):
    source_id: str
    tag: ProvenanceTag
    trust_level: TrustLevel
    chain_of_custody: List[str] = Field(default_factory=list)
    timestamp: float = Field(default_factory=time.time)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ToolCall(BaseModel):
    call_id: str
    tool_name: str
    arguments: Dict[str, Any]
    caller: str = "agent"


class PolicyDecision(BaseModel):
    allowed: bool
    rule_id: Optional[str] = None
    reason: str = "Allowed by policy"
    action: str = ""
    taint_records: List[ProvenanceRecord] = Field(default_factory=list)


class ToolResult(BaseModel):
    call_id: str
    tool_name: str
    status: str  # "SUCCESS", "BLOCKED_BY_POLICY", "ERROR"
    output: Any
    error: Optional[str] = None
    provenance: Optional[ProvenanceRecord] = None
    policy_decision: Optional[PolicyDecision] = None


class SnapshotMetadata(BaseModel):
    snapshot_id: str
    timestamp: float = Field(default_factory=time.time)
    description: str = ""
    file_hashes: Dict[str, str] = Field(default_factory=dict)
    taint_ledger_state: Dict[str, Any] = Field(default_factory=dict)


class Observation(BaseModel):
    step_id: int
    modified_files: List[str] = Field(default_factory=list)
    created_files: List[str] = Field(default_factory=list)
    deleted_files: List[str] = Field(default_factory=list)
    active_taint_count: int = 0
    tainted_resources: List[str] = Field(default_factory=list)
    provenance_context: Dict[str, Any] = Field(default_factory=dict)
